#!/usr/bin/env php
<?php
/**
 * Command-line code generation utility to automate programmer chores.
 *
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link          https://cakephp.org CakePHP(tm) Project
 * @package       app.Console
 * @since         CakePHP(tm) v 2.0
 * @license       https://opensource.org/licenses/mit-license.php MIT License
 */

if (!defined('DS')) {
    define('DS', DIRECTORY_SEPARATOR);
}

if (!defined('ROOT')) {
    define('ROOT', dirname(__DIR__, 2));
}

if (!defined('VENDORS')) {
    define('VENDORS', ROOT . DS . 'vendors' . DS);
}

if (!is_dir(VENDORS)) {
    trigger_error(
        'Composer vendors directory not found at "' . VENDORS . '". ' .
        'Please run "composer install" in the project root directory to install dependencies.',
        E_USER_ERROR
    );
}

if (!is_file(VENDORS . 'autoload.php')) {
    trigger_error(
        'Composer autoload file not found at "' . VENDORS . 'autoload.php". ' .
        'Please run "composer install" to generate the autoload file.',
        E_USER_ERROR
    );
}

require_once VENDORS . 'autoload.php';

if (!require_once 'Cake' . DS . 'Console' . DS . 'ShellDispatcher.php') {
    trigger_error('Could not locate CakePHP core files.', E_USER_ERROR);
}

return ShellDispatcher::run($argv);
